# Generated by Django 3.0 on 2021-05-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_updates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyupdate",
            name="description_bh",
            field=models.TextField(default="NA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dailyupdate",
            name="description_nbh",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
