# Generated by Django 3.0 on 2021-05-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily_updates", "0002_auto_20210520_1129"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyupdate",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="dailyupdate",
            name="billable",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dailyupdate",
            name="non_billable",
            field=models.IntegerField(default=0),
        ),
    ]
