# Generated by Django 3.0 on 2021-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="leave",
            name="approval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("denied", "denied"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
