# Generated by Django 3.0 on 2021-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0002_auto_20210527_0749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="approval",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("denied", "denied"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
