# Generated by Django 3.0 on 2021-05-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0003_auto_20210527_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="is_LOP",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leave",
            name="is_half_day",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="leave",
            name="from_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="leave",
            name="to_date",
            field=models.DateTimeField(),
        ),
    ]
