# Generated by Django 3.0 on 2021-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0004_auto_20210527_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="in_days",
            field=models.IntegerField(default=0),
        ),
    ]
