# Generated by Django 3.0 on 2021-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0005_leave_in_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="is_LOP",
        ),
        migrations.AddField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("compensatory", "compensatory"),
                    ("paid", "paid"),
                    ("unpaid", "unpaid"),
                ],
                default="compensatory",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="reason",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="leave",
            name="from_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="leave",
            name="to_date",
            field=models.DateField(),
        ),
    ]
