# Generated by Django 3.0 on 2021-06-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0007_auto_20210528_1900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("compensatory", "compensatory"),
                    ("leave", "leave"),
                    ("LOP", "LOP"),
                ],
                default="compensatory",
                max_length=20,
            ),
        ),
    ]
