# Generated by Django 3.0 on 2021-05-27 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20210511_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No role"),
                    ("admin", "Admin"),
                    ("human_resource", "HR"),
                    ("teamlead", "Teamlead"),
                    ("developer", "Developer"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
