# Generated by Django 3.0 on 2021-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210527_0709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No role"),
                    ("admin", "Admin"),
                    ("human_resource", "HR"),
                    ("teamlead", "Teamlead"),
                    ("developer", "Developer"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
