# Generated by Django 3.0 on 2021-05-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20210527_0710"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="remaining_leaves",
        ),
    ]
