# Generated by Django 3.0 on 2021-05-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_remaining_leaves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="total_leaves",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
