# Generated by Django 3.0 on 2021-05-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20210528_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="total_leaves",
            field=models.IntegerField(),
        ),
    ]
