# Generated by Django 3.0 on 2021-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20210528_1807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30, null=True, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30, null=True, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="total_leaves",
            field=models.IntegerField(null=True),
        ),
    ]
